### ISSUE TITLE
When calling Android 9 and below, the receiver has no sound

### ISSUE THREAD

**Issue by ShiXiaoXiang2019** [team-telnyx/telnyx-webrtc-android#125]
When using your SDK, the receiver of Android 9 and below has no sound during the call. Android 10 or 11 can call normally with normal sound. It seems that there is no such problem before. It has occurred recently

**Comment by Oliver-Zimmerman** [comment]
Hi @ShiXiaoXiang2019.

Can you please use the issue template we have set up on the repository? I'd like to know more about how this is occurring and which version of the SDK you are using, the device etc. 

There have been no recent code logic changes, just Gradle dependency version bumps in the last few weeks.

**Comment by tongsoftinfo** [comment]
I run the telnyx-webrtc-android project, add relevant configuration information, and then make a call, the first time is successful, after hanging up the phone, call again, there is no sound, it will appear on mobile phones below Android 10,
I tested on Android 9.0 and Android 8.0

**Comment by Oliver-Zimmerman** [comment]
> I run the telnyx-webrtc-android project, add relevant configuration information, and then make a call, the first time is successful, after hanging up the phone, call again, there is no sound, it will appear on mobile phones below Android 10, I tested on Android 9.0 and Android 8.0

When did you clone the repo? Is it happening with the up to date files?

**Comment by tongsoftinfo** [comment]
Download January 4th

**Comment by Oliver-Zimmerman** [comment]
> Download January 4th

Hi @tongsoftinfo 

Can you please try with the most up to date repo? I just ran a test with an Android 12 Pixel 5 device calling an Android 8.1 Nexus 6 and all seemed to be working.

I am closing this for now, if the problem persists please open another issue and use the **official bug template** which includes information such as whether you are testing with an emulator, etc.
