### ISSUE TITLE
[Bug] Short Bug Description

### ISSUE THREAD

**Issue by hpsolver** [team-telnyx/telnyx-webrtc-android#207]
**Bug Category**
- [ ] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [x ] Other

**SDK Version**
implementation 'com.github.team-telnyx:telnyx-webrtc-android:v1.2.15-alpha'

**Describe the bug**
When i received call Push notification and call successfully accepted and then receiver pressed call end button then caller not received any call ended or bye listener

**Expected behaviour**
Call should be end caller end also if receiver end the call

**To Reproduce**
Steps to reproduce the behaviour:
1. Receiver app should be in terminate state or killed
2. Accept call from notification and try to end call

**Android Device (please complete the following information):**
 - Emulator: (false)
 - Android Device: [e.g. OnePlus &T]
 - Android Version: [e.g. 11 ]

**Comment by Oliver-Zimmerman** [comment]
Hi @hpsolver.

This is a known issue that is related to the backend that is also affecting iOS. It shouldn't happen every time but we are aware it is happening.

Someone is actively looking into it at the moment. I will update you when I can.

**Comment by hpsolver** [comment]
in my app this issue always occurred Could you please help me to resolve this ASAP

**Comment by Oliver-Zimmerman** [comment]
@hpsolver as mentioned, we are aware of the issue and actively working to fix it. I will update you when I can

**Comment by Oliver-Zimmerman** [comment]
This has been resolved in the backend @hpsolver 

I am closing this for now.
