### ISSUE TITLE
[Bug] Unable to login on socket

### ISSUE THREAD

**Issue by hpsolver** [team-telnyx/telnyx-webrtc-android#208]
**Bug Category**
- [x] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [ ] Other

**SDK Version**
 implementation 'com.github.team-telnyx:telnyx-webrtc-android:v1.2.15-alpha'

**Describe the bug**
Unable to login on socket . It toast error "Gateway registration failed"

**Expected behaviour**

**To Reproduce**
Steps to reproduce the behaviour:
1. Log on with credentials
2. Socket error then returned

**Android Device (please complete the following information):**
 - Emulator: (false)
 - Android Device: One Plus 7T

**Logs**
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/25339734/187205464-1727bdc9-5305-4bbf-a52b-ce96268e2389.png">
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/25339734/187205619-0b207367-3d75-4525-9a7c-0a5b0d6c0272.png">
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/25339734/187205725-f54afb13-c112-4c90-880c-4c7f7de9594b.png">
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/25339734/187205821-0a0f52fd-4dca-45ee-9414-1d839ad9c13e.png">
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/25339734/187205879-dd20075d-d7a6-4275-9252-d8514380c3ea.png">

**Comment by Oliver-Zimmerman** [comment]
Hi @hpsolver 

Are you using the sample application or your own implementation?

**Comment by hpsolver** [comment]
own implementation

**Comment by Oliver-Zimmerman** [comment]
Okay, can you confirm if it is also happening on the sample app?
We also have a new version of the SDK that will be released later today that adjusts how we handle connectivity that might resolve your issue. The PR is here:
https://github.com/team-telnyx/telnyx-webrtc-android/pull/205

**Comment by hpsolver** [comment]
no it’s not happening in sample app

**Comment by Oliver-Zimmerman** [comment]
In that case would you be able to share snippets of your code relating to connect and log on? @hpsolver

**Comment by hpsolver** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/25339734/187234965-e3de5e05-d56e-4a28-9c9a-ff12ba2c4f7e.png">

**Comment by hpsolver** [comment]
fun doLoginWithCredentials(userName: String?, number: String?, fcmToken: String?, sipUserName: String, sipPassword: String) {
        val loginConfig = CredentialConfig(
                sipUserName,
                sipPassword,
                userName,
                number,
                fcmToken,
                null,
                R.raw.ringback_tone,
                LogLevel.ALL
        )
        telnyxClient?.credentialLogin(loginConfig)
    }

**Comment by Oliver-Zimmerman** [comment]
Is initConnection or doLoginWithCredentials being called multiple times? You will receive UNREGED if a user logs in with your credentials again (only one user can be logged in at a time if you're using the SIP Connection username and password)

**Comment by hpsolver** [comment]
initConnection and doLoginWithCredentials called only once when app launched.But if i have 2 devices and in which i logged with same credentials then this issue can occurred ?

**Comment by Oliver-Zimmerman** [comment]
@hpsolver did this solve your issue? Can I close?
