### ISSUE TITLE
[Bug] Short Bug Description

### ISSUE THREAD

**Issue by simple-scanner** [team-telnyx/telnyx-webrtc-android#239]
**Bug Category**
- [x] Credential Login                     true
- [ ] Token Login                             false
- [x] Local Audio Issue                    true
- [x] Remote Audio Issue                true
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [ ] Other

**SDK Version**
Which version of the SDK have you added from Jitpack? Feel free to add the whole dependency implementation:
eg. implementation 'com.github.team-telnyx:telnyx-webrtc-android:v1.2.12-alpha'
sdk version v1.2.1.16

**Describe the bug**

1.At first, we could log in normally, but now we can't even log in. What we need to solve now is the problem of online apps
2.After a period of outbound call, the time is about 50s. The voice media transmission stops, but the outbound call will not be interrupted

**Expected behaviour**

Normal call No matter how long the call lasts, the voice media will not be interrupted

**To Reproduce**
Steps to reproduce the behaviour:
1. e.g. (Log on with credentials)    Login with on-demand credentials
2. e.g. (Socket error then returned)

**Android Device (please complete the following information):**
 - Emulator: (true/false)     false
 - Android Device: [e.g. Pixel 6]     SM-G9500
 - Android Version: [e.g. 12 ]          android 9

**Logs**
Please provide any logs available to you, remember to enable verbose logging within the SDK. It is generally helpful to filter by either TxSocket (Socket messages) or TelnyxClient (Client messages) or both depending on the situation.

2022-10-28 12:00:06.845 20472-20569/com.telnyx.webrtc.sdk I/TxSocket: Socket is closed: null java.net.UnknownHostException: Unable to resolve host "rtc.telnyx.com": No address associated with hostname :: Will attempt to reconnect

2022-10-28 12:00:06.699 20472-20565/com.telnyx.webrtc.sdk D/TelnyxClient$networkCallback: [TelnyxClient] :: There is a network available

**Comment by isaacakakpo1** [comment]
Closing Stale Issue
