### ISSUE TITLE
[Bug] Short Bug Description

### ISSUE THREAD

**Issue by JunZhangNext** [team-telnyx/telnyx-webrtc-android#243]
**Bug Category**
- [ ] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [x] Other

**SDK Version**
implementation 'com.github.team-telnyx:telnyx-webrtc-android:v1.2.12-alpha'

**Describe the bug**
Google detected a warning about WebRTC when we released the Android version and needs to fix it
There is a bug in the version of WebRTC used, which has a security vulnerability.
Details can be found here 
https://support.google.com/faqs/answer/12577537

**Expected behaviour**
Just fix the WebRTC

**To Reproduce**
None

**Android Device (please complete the following information):**
 - Emulator: (true/false)
 - Android Device: [e.g. Pixel 6]
 - Android Version: [e.g. 12 ]

**Logs**
None

**Comment by isaacakakpo1** [comment]
@JunZhangNext there's a new release https://github.com/team-telnyx/telnyx-webrtc-android/releases/tag/1.3.0.
