### ISSUE TITLE
Migrate to Flow?

### ISSUE THREAD

**Issue by Del-S** [team-telnyx/telnyx-webrtc-android#305]
Do you plan to migrate away from `LiveData` to `Flow`? Using LiveData in Flow based application is kinda messy. Also `LiveData` are still nullable which can create additional edge-cases in the app.

**Comment by isaacakakpo1** [comment]
Hello, @Del-S . Yes we're planning on migrating to flow for our next major release. You can still however try the `asflow` extension method that converts livedata to flows. 

Checkout this repo too, it has a flow usage of the library  
https://github.com/develNerd/TelnyxAndroidClient/blob/main/app/src/main/java/org/telnyx/androidclient/usecases/GetSocketResponseUseCase.kt

**Comment by Del-S** [comment]
Hey. Ah good to know. Thank you.

Yeah I know about the the Extension. It creates a global observer which I did not want to do so I am adding an observer and removing it when I need to. But thanks anyway. Can't wait for the flow migration.
