### ISSUE TITLE
[Bug] Received FCM notification for call with connected socket (socket did not receive the information).

### ISSUE THREAD

**Issue by Del-S** [team-telnyx/telnyx-webrtc-android#309]
**Bug Category**
- [x] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [ ] Other

**SDK Version**
implementation 'com.github.team-telnyx:telnyx-webrtc-android:v1.2.21-alpha'

**Describe the bug**
App is started and connected to socket. Incoming call is send using FCM instead into the socket directly.

**Expected behaviour**
Socket receives the call and no FCM notification is posted.

**To Reproduce**
Not really sure how I got into this state actually.

I believe my app crashed because it was not able to send Bye to socket.
Then I tried calling to the app (to receive FCM notification) which did not arrive at the time.
Incoming call then auto closed.
Then I started the app and it received the call notification (for call that does not exists anymore).
I tried to cancel the call but I was not able to since it does not exist anymore.
And then I tried calling again to the app in the foreground and this happened.

**Android Device (please complete the following information):**
 - Emulator: true
 
**Logs**
Please provide any logs available to you, remember to enable verbose logging within the SDK. It is generally helpful to filter by either TxSocket (Socket messages) or TelnyxClient (Client messages) or both depending on the situation.

Connected socket in the app:
```
2023-07-07 13:34:52.497 14433-14522 VERTO                   com.second.phone.number.staging      D  [TxSocket] Receiving [{"jsonrpc":"2.0","id":29348,"method":"telnyx_rtc.ping","params":{"serno":1688729693}}]
2023-07-07 13:34:52.499 14433-14522 VERTO                   com.second.phone.number.staging      D  [TxSocket] Received Method [telnyx_rtc.ping]
2023-07-07 13:34:52.501 14433-14522 TelnyxClient            com.second.phone.number.staging      D  [TelnyxClient] :: pingPong 
2023-07-07 13:34:52.542 14433-14522 VERTO                   com.second.phone.number.staging      D  [TxSocket] Receiving [{"jsonrpc":"2.0","id":29348,"result":{"message":"PONG","sessid":"6b9e87c1-8f38-4a84-9be7-e28f75aa75d9"}}]
2023-07-07 13:35:03.348 14433-14522 VERTO                   com.second.phone.number.staging      D  [TxSocket] Receiving [{"jsonrpc":"2.0","id":29417,"method":"telnyx_rtc.gatewayState","params":{"state":"TRYING"}}]
2023-07-07 13:35:03.349 14433-14522 VERTO                   com.second.phone.number.staging      D  [TxSocket] Receiving [{"jsonrpc":"2.0","id":29419,"method":"telnyx_rtc.gatewayState","params":{"state":"REGISTER"}}]
2023-07-07 13:35:04.269 14433-14522 VERTO                   com.second.phone.number.staging      D  [TxSocket] Receiving [{"jsonrpc":"2.0","id":29423,"method":"telnyx_rtc.gatewayState","params":{"state":"REGED"}}]
2023-07-07 13:35:04.269 14433-14522 TelnyxClient            com.second.phone.number.staging      D  [TelnyxClient] :: onLoginSuccessful :: [6b9e87c1-8f38-4a84-9be7-e28f75aa75d9] :: Ready to make calls
```

But notification is received instead of directly updating socket:

```
2023-07-07 13:35:06.959 14433-15165 SpnFirebas...ingService com.second.phone.number.staging      D  SpnFirebaseMessagingService.onMessageReceived(com.google.firebase.messaging.RemoteMessage@b55637e)
2023-07-07 13:35:06.960 14433-15165 SpnFirebas...ingService com.second.phone.number.staging      D  handleDataMessage({metadata={"caller_name":"420732652757","caller_number":"420732652757","call_id":"b7893ab5-616d-4943-a77b-484fb850e75c"}, message=Incoming call!})
```

It worked properly for the second call.

**Comment by isaacakakpo1** [comment]
Hello @Del-S can you confirm is this issue is fixed in 
https://github.com/team-telnyx/telnyx-webrtc-android/releases/tag/1.2.6

**Comment by Del-S** [comment]
Can you please deploy the SDK? It was here https://jitpack.io/#team-telnyx/telnyx-webrtc-android but last version is still 1.2.22-alpha. Or did you start deploying somewhere else?

**Comment by isaacakakpo1** [comment]
This is because 1.2.22-alpha is an alpha version. Kindly take a look at https://github.com/team-telnyx/telnyx-webrtc-android/releases/tag/1.2.8 
`implementation 'com.github.team-telnyx:telnyx-webrtc-android:1.2.8'` Android studio would suggest `1.2.8` as the latest.   

This would be fixed in our next release on Jitpack as well. Thanks

**Comment by Del-S** [comment]
Ah you stripped the `v` from the version name. That is why it did not work for me. Also it is pretty weird to see **1.2.22-alpha** at the top of the `https://jitpack.io/#team-telnyx/telnyx-webrtc-android`.

**Comment by isaacakakpo1** [comment]
Yes the `v` was deprecated. Most gradle libraries do not not have the `v` any longer.  Yes `1.2.22-alpha` should not be at the top. It will be resolved in the next release

**Comment by Del-S** [comment]
So I cannot test this since I am not receiving FCM notifications. I get the socket call correctly:

```
[TxSocket] Receiving [{"jsonrpc":"2.0","id":56445,"method":"telnyx_rtc.invite","params":{"callID":"e55b4004-16ee-4333-91ca-046212d2045c","variables":{"Event-Name":"CHANNEL_DATA","Core-UUID":"4c37c23e-906e-441d-8a32-22c0860e1117","FreeSWITCH-Hostname":"b2bua-rtc.tel-ld6-ibm-prod-368","FreeSWITCH-Switchname":"b2bua-rtc.tel-ld6-ibm-prod-368","FreeSWITCH-IPv4":"10.31.18.80","FreeSWITCH-IPv6":"::1","Event-Date-Local":"2023-11-21 12:21:32","Event-Date-GMT":"Tue, 21 Nov 2023 12:21:32 GMT","Event-Date-Timestamp":"1700569292004613","Event-Calling-File":"switch_channel.c","Event-Calling-Function":"switch_channel_get_variables_prefix","Event-Calling-Line-Number":"4631","Event-Sequence":"131332"},"sdp":"v=0\r\no=FreeSWITCH 1700550390 1700550391 IN IP4 185.246.41.183\r\ns=FreeSWITCH\r\nc=IN IP4 185.246.41.183\r\nt=0 0\r\na=msid-semantic: WMS Lt1f399tEzMdmX0mnAikeGdEAI0mzgVb\r\nm=audio 18902 RTP/SAVPF 0 8 102\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:102 opus/48000/2\r\na=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40\r\na=fingerprint:sha-256 68:75:9F:A3:51:A1:EB:61:5A:0E:6F:BA:C9:BC:E4:60:6D:9B:7C:5F:28:7A:3D:01:56:C3:DF:89:49:80:40:4A\r\na=setup:actpass\r\na=rtcp-mux\r\na=rtcp:18902 IN IP4 185.246.41.183\r\na=ssrc:1432263100 cname:AMhuLhNgHqkTda6r\r\na=ssrc:1432263100 msid:Lt1f399tEzMdmX0mnAikeGdEAI0mzgVb a0\r\na=ssrc:1432263100 mslabel:Lt1f399tEzMdmX0mnAikeGdEAI0mzgVb\r\na=ssrc:1432263100 label:Lt1f399tEzMdmX0mnAikeGdEAI0mzgVba0\r\na=ice-ufrag:AeCFKFabe0oE79Gx\r\na=ice-pwd:MNSnUvurLEbPF775bzBM4BO9\r\na=candidate:7470635790 1 udp 2130706431 185.246.41.183 18902 typ host generation 0\r\na=candidate:7470635790 2 udp 2130706431 185.246.41.183 18902 typ host generation 0\r\na=silenceSupp:off - - - -\r\na=ptime:20\r\na=sendrecv\r\nm=video 18904 RTP/SAVPF 103\r\nb=AS:1024\r\na=rtpmap:103 VP8/90000\r\na=mid:video\r\na=sendrecv\r\na=fingerprint:sha-256 68:75:9F:A3:51:A1:EB:61:5A:0E:6F:BA:C9:BC:E4:60:6D:9B:7C:5F:28:7A:3D:01:56:C3:DF:89:49:80:40:4A\r\na=setup:actpass\r\na=rtcp-mux\r\na=rtcp:18904 IN IP4 185.246.41.183\r\na=rtcp-fb:103 ccm fir\r\na=rtcp-fb:103 ccm tmmbr\r\na=rtcp-fb:103 nack\r\na=rtcp-fb:103 nack pli\r\na=ssrc:582000302 cname:AMhuLhNgHqkTda6r\r\na=ssrc:582000302 msid:Lt1f399tEzMdmX0mnAikeGdEAI0mzgVb v0\r\na=ssrc:582000302 mslabel:Lt1f399tEzMdmX0mnAikeGdEAI0mzgVb\r\na=ssrc:582000302 label:Lt1f399tEzMdmX0mnAikeGdEAI0mzgVbv0\r\na=ice-ufrag:y8ZgbGAIoAL4xJMT\r\na=ice-pwd:97a06r9YcyIYBXoZWd6XKxwY\r\na=candidate:3223027601 1 udp 2130706431 185.246.41.183 18904 typ host generation 0\r\na=candidate:3223027601 2 udp 2130706430 185.246.41.183 18904 typ host generation 0\r\na=end-of-candidates\r\n","caller_id_name":"420732652757","caller_id_number":"420732652757","callee_id_name":"Outbound Call","callee_id_number":"davidSucharda","telnyx_session_id":"8113f8c8-8868-11ee-b736-02420a1f0d69","telnyx_leg_id":"811a29e6-8868-11ee-914c-02420a1f0d69","display_direction":"outbound","dialogParams":{"custom_headers":[]}}}]
```

But when I kill the app and call again, no FCM notification is received. :/

**Comment by isaacakakpo1** [comment]
This is because the callee (`+17162689591`) does not have push notification enabled. can you confirm this from the backend side ? Yes it is related

**Comment by Del-S** [comment]
Yep it seems to be configuration issue. I do not have permissions to fix it so I gonna have to contact someone that can. Gonna keep you posted. Thanks.

**Comment by Del-S** [comment]
Ok so I tried the changes. I received this notification:

```
{metadata={"caller_name":"420732652757","voice_sdk_id":"VSDK1Ch8iUDpaSNgZUzziQ2unwF-nADL3Ig","dialogParams":{"custom_headers":[]},"rtc_port":14938,"rtc_ip":"10.31.34.80","caller_number":"420732652757","call_id":"433b4879-0cd9-447e-bd73-de9e0fc379b4"}, message=Incoming call!}
```

I used the `voice_sdk_id: VSDK1Ch8iUDpaSNgZUzziQ2unwF-nADL3Ig` and tried to connect with it using something like this: `TelnyxClient(context).connect(txPushMetaData = "VSDK1Ch8iUDpaSNgZUzziQ2unwF-nADL3Ig")`. And it unfortunatelly crashes on me during json parsing:

```
FATAL EXCEPTION: DefaultDispatcher-worker-3
  Process: com.second.phone.number.dev, PID: 10441
  com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
   at com.google.gson.Gson.fromJson(Gson.java:963)
   at com.google.gson.Gson.fromJson(Gson.java:928)
   at com.google.gson.Gson.fromJson(Gson.java:877)
   at com.google.gson.Gson.fromJson(Gson.java:848)
   at com.telnyx.webrtc.sdk.TelnyxClient.connect(TelnyxClient.kt:249)
   at com.telnyx.webrtc.sdk.TelnyxClient.connect$default(TelnyxClient.kt:243)
```

Unfortunatelly it did not log the body that it is trying to convert. So I got two questions:
1) Am I doing this correctly? Taking the SDK ID and putting it as metadata to connection.
2) Why is it crashing?

Thank you for your help.

**Comment by Del-S** [comment]
Ok this seems fine now.
