### ISSUE TITLE
How to update firebase token?

### ISSUE THREAD

**Issue by Del-S** [team-telnyx/telnyx-webrtc-android#320]
So is there a way to update firebase token in the SDK? I only see firebase token updates using login. But it does not seem right to force new login when firebase token changes. Can there be an option to update only the token without the need to login again?

**Comment by isaacakakpo1** [comment]
@Del-S we currently only support updating the FCM Token at login (at least from the client side). Also I believe FCM tokens change usually in scenarios like Clearing Storage Data or Uninstalling the App. Is there a particular use-case you consider this an important feature ?

**Comment by Del-S** [comment]
Okay so the cases based on the docu are like this:

> The registration token may change when:
> - The app is restored on a new device
> - The user uninstalls/reinstall the app
> - The user clears app data.

So I guess we care about reinstall or restore since those can restore app data. In those cases if user does that. It would be expected that user can still receive FCM notifications for incomming calls. To support this currently we would have to login to telnyx which creates a socket that receives the calls so again we do not receive fcm notifications. 

So I guess the only option is to `connect - login - logout and disconnect`. Which seems like a hassle to just update FCM token. I would expect a function which will have user credentials and new fcm token which will update it on the telnyx side without the need to create a socket connection.

**Comment by Del-S** [comment]
Nice thanks.

**Comment by Del-S** [comment]
Ok then. Thank you for the information. :)
