### ISSUE TITLE
[Bug] Upgrade Volley to 1.2.0

### ISSUE THREAD

**Issue by joshbartley** [team-telnyx/telnyx-webrtc-android#334]
**Bug Category**
- [ x] Other

**SDK Version**
1.2.7

**Describe the bug**
Due to the migration of volley to maven, version 1.1.1 no longer exists in most maven repositories. Newer versions are backwards compatible according to the devs.

**Expected behaviour**
Should be able to install the package using maven.

**To Reproduce**
Fresh install, attempt to install the package.
 

**Logs**
Available Volley versions.

https://maven.google.com/web/index.html?q=com.android.volley#com.android.volley:volley

https://github.com/google/volley/issues/394

**Comment by isaacakakpo1** [comment]
@joshbartley this issue is fixed in release https://github.com/team-telnyx/telnyx-webrtc-android/releases/tag/1.3.0
